name: Compile LaTeX on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup LaTeX
      uses: docker://blang/latex:ubuntu

    - name: Compile LaTeX
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
        # Add more commands if needed, e.g., bibtex, makeindex, etc.

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: main.pdf
